In [ ]:
#Preprocessing Data Pipeline

In [1]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer,WordNetLemmatizer
from nltk.corpus import stopwords
import re
import pandas as pd

In [2]:
data=pd.read_csv('tripadvisor_hotel_reviews.csv')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  109 non-null    object
 1   Rating  109 non-null    int64
dtypes: int64(1), object(1)
memory usage: 1.8+ KB

In [7]:
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [9]:
data['Review'][0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews did valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe just noisy neighbors, aveda bath products nice, did not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience having pay 40 parking night,  '

In [12]:
data['review_lowercase']=data['Review'].str.lower()

In [14]:
data.head()

                                              Review  ...                                   review_lowercase
0  nice hotel expensive parking got good deal sta...  ...  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...  ...  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...  ...  nice rooms not 4* experience hotel monaco seat...
3  unique, great stay, wonderful time hotel monac...  ...  unique, great stay, wonderful time hotel monac...
4  great stay great stay, went seahawk game aweso...  ...  great stay great stay, went seahawk game aweso...

[5 rows x 3 columns]

In [15]:
en_stopwords=stopwords.words('english')

In [16]:
en_stopwords.remove("not")

In [19]:
data["review_no_stopwords"]=data['review_lowercase'].apply(lambda x:" ".join([word for word in x.split() if word not in (en_stopwords)]))

In [21]:
data.head()

                                              Review  ...                                review_no_stopwords
0  nice hotel expensive parking got good deal sta...  ...  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...  ...  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...  ...  nice rooms not 4* experience hotel monaco seat...
3  unique, great stay, wonderful time hotel monac...  ...  unique, great stay, wonderful time hotel monac...
4  great stay great stay, went seahawk game aweso...  ...  great stay great stay, went seahawk game aweso...

[5 rows x 4 columns]

In [23]:
data['review_no_stopwords'][0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe noisy neighbors, aveda bath products nice, not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience pay 40 parking night,'

In [25]:
data['review_no_stopwords_no_puct']=data.apply(lambda x: re.sub(r"[*]","star",x['review_no_stopwords']),axis=1)

In [27]:
data['review_no_stopwords_no_puct'][2]

"nice rooms not 4star experience hotel monaco seattle good hotel n't 4star level.positives large bathroom mediterranean suite comfortable bed pillowsattentive housekeeping staffnegatives ac unit malfunctioned stay desk disorganized, missed 3 separate wakeup calls, concierge busy hard touch, n't provide guidance special requests.tv hard use ipod sound dock suite non functioning. decided book mediterranean suite 3 night weekend stay 1st choice rest party filled, comparison w spent 45 night larger square footage room great soaking tub whirlpool jets nice shower.before stay hotel arrange car service price 53 tip reasonable driver waiting arrival.checkin easy downside room picked 2 person jacuzi tub bath accessories salts bubble bath n't stay, night got 12/1a checked voucher bottle champagne nice gesture fish waiting room, impression room huge open space felt room big, tv far away bed chore change channel, ipod dock broken disappointing.in morning way asked desk check thermostat said 65f 74 2 degrees warm try cover face night bright blue light kept, got room night no, 1st drop desk, called maintainence came look thermostat told play settings happy digital box wo n't work, asked wakeup 10am morning n't happen, called later 6pm nap wakeup forgot, 10am wakeup morning yep forgotten.the bathroom facilities great room surprised room sold whirlpool bath tub n't bath amenities, great relax water jets going,"

In [29]:
data.head()

                                              Review  ...                        review_no_stopwords_no_puct
0  nice hotel expensive parking got good deal sta...  ...  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...  ...  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...  ...  nice rooms not 4star experience hotel monaco s...
3  unique, great stay, wonderful time hotel monac...  ...  unique, great stay, wonderful time hotel monac...
4  great stay great stay, went seahawk game aweso...  ...  great stay great stay, went seahawk game aweso...

[5 rows x 5 columns]

In [31]:
data['review_no_stopwords_no_puct']=data.apply(lambda x: re.sub(r"([^\w\s])","",x['review_no_stopwords_no_puct']),axis=1)

In [33]:
data['tokenized']=data.apply(lambda x:word_tokenize(x['review_no_stopwords_no_puct']),axis=1)

In [ ]:
data['tokenized'][0]

In [39]:
ps=PorterStemmer()
data['stemmed']=data['tokenized'].apply(lambda tokens :[ps.stem(token) for token in tokens])

In [ ]:
data.head()

In [42]:
lemmatizer=WordNetLemmatizer()

In [44]:
data['lemmatized']=data['tokenized'].apply(lambda tokens :[lemmatizer.lemmatize(token) for token in tokens])

In [ ]:
data.head()

In [47]:
token_clean=sum(data['lemmatized'],[])

In [49]:
unigrams= (pd.Series(nltk.ngrams(token_clean,1)).value_counts())
print(unigrams)

(hotel,)           292
(room,)            275
(great,)           126
(not,)             122
(stay,)             95
                  ...
(175,)               1
(smackagainst,)      1
(2x,)                1
(80,)                1
(connected,)         1
Name: count, Length: 2589, dtype: int64

In [51]:
biggrams= (pd.Series(nltk.ngrams(token_clean,2)).value_counts())
print(biggrams)

(great, location)     24
(space, needle)       21
(hotel, monaco)       16
(great, hotel)        12
(staff, friendly)     12
                      ..
(didnt, make)          1
(personnel, didnt)     1
(minute, stay)         1
(starting, minute)     1
(food, raffle)         1
Name: count, Length: 8263, dtype: int64